### ISSUE TITLE
Passing map data!

### ISSUE THREAD

**Issue by ghost** [jhester/DistributedGA#2]
Currently we are pickling the list part of the map data class and sending that, then creating a different map class clientside and modifying the class in an unsafe way.  We need a better system to send/reconstruct map data.

**Comment by jhester** [comment]
Maybe we should just use strings and parse it out in the code. Pickle caused more problems than it solved for most of the groups.  Maybe just send raw data,and use a simple string parser.

**Comment by jhester** [comment]
http://nadiana.com/python-pickle-insecure
Pickle sucks.

http://stackoverflow.com/questions/1336908/python-alternatives-to-pickling-a-module
We could use JSON, which is included in python as a standard after 2.6, or structs. Need to research that though.

**Comment by ghost** [comment]
We have to use Pyhon 2.4, and if we want to use condor we can't install extras :( Structs seem simple, but might be a little annoying to work with.  Still Structs seem to be the best bet, you can't just stick a list in them though.

**Comment by jhester** [comment]
I am finishing up the graphical side of the observer using tilemaps, I made it so that we can just pass an ascii file (with line breaks) and it should be able to break up everything.  So we may not even have to use structs or fancy dtata structures.  Here an example of the maps that Im taking now.

154215550004411355140
445440213412014505032
301445333151451035124
002544325431145325113
521225045103445054144
154215550004411355140
445440213412014505032
301445333151451035124
002544325431145325113
521225045103445054144

This assumes that you have 6 different types of tile images.

**Comment by jhester** [comment]
Im going to close this issue in favor of a new one. We need to decide whether we want to auto generate the map or predefine it in levels in text files.
